### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by jogibear9988** [vpotseluyko/mjs-mocha#10]
does not work on windows, bin/sh not found ;-(

**Comment by vpotseluyko** [comment]
Oh hi
I can try to fix it, but you’ll have to help me with tests. That’s ok?

**Comment by vpotseluyko** [comment]
Problem is here, we’ve failed with correct shebang
https://github.com/vpotseluyko/mjs-mocha/blob/master/src/shebang.mjs

**Comment by vpotseluyko** [comment]
The correct one should be
#!/usr/bin/env node

Can you plz clone master, change one and give a feedback?

**Comment by jogibear9988** [comment]
will do

**Comment by jogibear9988** [comment]
if i'll try this:

	#!/usr/bin/env node
	":" // ; exec node --experimental-modules --no-warnings "$0" "$@"

	import index from '.'

	index();

same error:

Der Befehl "/bin/sh" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! Test failed.  See above for more details.

**Comment by jogibear9988** [comment]
mhmm... don't know what i do wrong
chaged shebang.mjs in node_modules, but same error. even if i delete /bin/sh from shebang.mjs

**Comment by romap0** [comment]
@jogibear9988 Please check out code from PR https://github.com/vpotseluyko/mjs-mocha/pull/12
For me it works on Windows

**Comment by jogibear9988** [comment]
Don't know what im doing wrong...

downloaded your branch and replaces everything in node_modules\mjs-moch with your code

added "test": "mjs-mocha" to my package.json

run npm test

i still get:

> mcc-ui@ test F:\csharp\git\mcc5\MCC.V1.0\1PL\HTML
> mjs-mocha

Der Befehl "/bin/sh" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! Test failed.  See above for more details.

but i do not find /bin/sh in your code

**Comment by jogibear9988** [comment]
if I run index.js directly, it seems to work:

F:\csharp\git\mcc5\MCC.V1.0\1PL\HTML>node node_modules\mjs-mocha\src\index.js

 ✔ All 0 test suites passed


F:\csharp\git\mcc5\MCC.V1.0\1PL\HTML>

**Comment by romap0** [comment]
Remove mjs-mocha package and install it using `npm i https://github.com/romap0/mjs-mocha#fix-shebang`

**Comment by jogibear9988** [comment]
now it works ...

but why does it not work when I copy directly?

**Comment by jogibear9988** [comment]
Now I got this error

	F:\csharp\git\mcc5\MCC.V1.0\1PL\HTML>npm test

	> mcc-ui@ test F:\csharp\git\mcc5\MCC.V1.0\1PL\HTML
	> mjs-mocha

	{ Error: Cannot find module node_modules/mjs-mocha/src/loader.mjs
		at search (internal/modules/esm/default_resolve.js:29:12)
		at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
		at Loader.resolve (internal/modules/esm/loader.js:58:33)
		at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
		at Loader.import (internal/modules/esm/loader.js:99:28)
		at loaderPromise (internal/process/esm_loader.js:53:43)
		at Object.exports.setup (internal/process/esm_loader.js:60:5)
		at startup (internal/bootstrap/node.js:184:59)
		at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) code: 'MODULE_NOT_FOUND' }


	 ✗ 1/1 test suites failed

	npm ERR! Test failed.  See above for more details.

package.json:

    "test": "mjs-mocha"

test file common.test.mjs:

	import { expect } from "chai";
	import { UUID } from "../dist/libs/uuid/uuid";

	describe('common tests', () => {
		it('uuid test', () => {
			let result = UUID.genV1();
			expect(result).equal('aaa');
		});
	});

**Comment by jogibear9988** [comment]
Problem is, loader path needs to start with "./"

**Comment by jogibear9988** [comment]
if change 

    const test = cp.spawn('node', [
    ...customNodeArgs,
    '--no-warnings',
    '--experimental-modules',
    '--loader',
    './' + loaderPath,
    testFilePath,
  ]

it works

**Comment by jogibear9988** [comment]
but I still have the problem that in .js files the imports will not work.

isn't it possible to support this in the loader?

or will it work in two weeks with node 12? https://twitter.com/nodemjs/status/1111006936756092930

**Comment by vpotseluyko** [comment]
what node do u run? originally this module was written for node v8. We surely have to check what happens with later node versions

**Comment by jogibear9988** [comment]
node 10

**Comment by jogibear9988** [comment]
maybe you can check if adding "./" also works on node 8

**Comment by vpotseluyko** [comment]
Can u please create test repo with reproducer? That will be great help and will speed process very much

**Comment by jogibear9988** [comment]
jup, i'll will do

**Comment by jogibear9988** [comment]
not workin tests:

https://ci.appveyor.com/project/jogibear9988/mjs-mocha-test/builds/23782364

workin after my fix:

https://ci.appveyor.com/project/jogibear9988/mjs-mocha-test/builds/23782406

okay, you see both do not work. but the second one fails the test because I think I have not included chai

the repo is at: 
https://github.com/jogibear9988/mjs-mocha-test/commits/master

**Comment by vpotseluyko** [comment]
please do `npm i mjs-mocha@latest` and confirm that't everything is ok

**Comment by vpotseluyko** [comment]
suddenly `./` was rather rude, but idea was correct. I've used `process.cwd()` for fix.

**Comment by jogibear9988** [comment]
again, does not work

error:

Error [ERR_MODULE_RESOLUTION_LEGACY]: F:\csharp\git\github\mjs-mocha-test\node_modules\mjs-mocha\src\loader.mjs not found by import in file:///F:/csharp/git/github/mjs-mocha-test/. Legacy behavior in require() would have found it at F:\csharp\git\github\mjs-mocha-test\node_modules\mjs-mocha\src\loader.mjs
    at search (internal/modules/esm/default_resolve.js:39:15)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at loaderPromise (internal/process/esm_loader.js:53:43)
    at Object.exports.setup (internal/process/esm_loader.js:60:5)
    at startup (internal/bootstrap/node.js:184:59)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

if you use a absolute path, you need to add 'file://' then it works

**Comment by jogibear9988** [comment]
and also 

    npm i mjs-mocha@latest 

did not work, I need to

    npm i mjs-mocha@2.2.3

don't know why

**Comment by vpotseluyko** [comment]
sad thing is this works on node 8.15.0 on mac os, but I can reproduce your error in ci. Still looking into it. Thanks

**Comment by jogibear9988** [comment]
try my fix with file://

**Comment by vpotseluyko** [comment]
ok, you right

version `2.2.4` is on npm

working repo: https://github.com/vpotseluyko/mjs-mocha-test

**Comment by vpotseluyko** [comment]
@jogibear9988 can u confirm everything is ok?
