### ISSUE TITLE
how to use with typescript tests

### ISSUE THREAD

**Issue by jogibear9988** [vpotseluyko/mjs-mocha#11]
with mocha and typescript compiled to es5 i could do this

    mocha -r ts-node/register tests/**/*.test.ts

how could i do this with mjs-mocha?

**Comment by vpotseluyko** [comment]
No way here. If only you’ll run it with ts-node or smth like.

**Comment by vpotseluyko** [comment]
Meanwhile we use if eith flow. We just compile flow before tests

**Comment by jogibear9988** [comment]
??? i'll use ts-node

**Comment by jogibear9988** [comment]
I'll compile Typescript to ES6

**Comment by romap0** [comment]
I think you will also need to change extension of your ES6 files to `.mjs` to run tests via mjs-mocha

**Comment by jogibear9988** [comment]
why? you can ignore the ext in your loader

**Comment by jogibear9988** [comment]
Is it possible that the loader also loads when extension is .js? or what does ts-node return?

**Comment by vpotseluyko** [comment]
when using ts -> js compiler you surely do not use mjs modules and can use usual mocha

**Comment by vpotseluyko** [comment]
when u really compile ts to mjs files, u have to import already built files for tests. No native ts support will be provided for now, sorry

**Comment by jogibear9988** [comment]
i use ts -> js compiler. and you can configure ts compiler to compile to es6 modules by setting 

    "target": "ES2017",                      
    "module": "es2015",             

but it will create .js files.

only thing that needs to be changed (i thought), is that your loader also loads .js files as mjs. ithought this would be possible if you return format 'esm', see https://nodejs.org/api/esm.html#esm_loader_hooks

**Comment by vpotseluyko** [comment]
So I’ll reopen and look into if u can bring repo with reproducer

**Comment by jogibear9988** [comment]
kay, i'll look

**Comment by jogibear9988** [comment]
when the windows version works, I'll create a repo and try to create a fix

**Comment by vpotseluyko** [comment]
windows version must work. Waitin' for reproducer

**Comment by jogibear9988** [comment]
seems not so easy to fix so that -require ts-node/register would work.

but maybe you could change index.js, so that we can tell in wich files to search (so .mjs is not hardcoded?)

**Comment by vpotseluyko** [comment]
Can u plz create simple reproducer? I’ll try to figure out the problem

**Comment by jogibear9988** [comment]
think you do not support the —requires parameter as mocha does.
Don‘t know how it works inside of mocha..,

**Comment by vpotseluyko** [comment]
I still need reproducer cause without code I couldn't really address yours certain issue. Meanwhile I'm not great ts fan, so it'll take bunch of time to recreate your situation from scratch

**Comment by jogibear9988** [comment]
i don't know how to create an repro, because --requires seems not supported from mjs-mocha.

see, normaly you use tsnode like this
(https://github.com/TypeStrong/ts-node)

     mocha --require ts-node/register --watch-extensions ts,tsx "test/**/*.{ts,tsx}" [...args]

and then mocha loads them in a special way:

https://github.com/mochajs/mocha/blob/f1fe632a5aca224994fa8c1240be6852bec236a8/lib/cli/node-flags.js#L47
https://github.com/mochajs/mocha/blob/f1fe632a5aca224994fa8c1240be6852bec236a8/lib/cli/run-helpers.js#L109

**Comment by vpotseluyko** [comment]
for now we won't support this feature

this may come in future releases or never. Meanwhile feel free to open pr

**Comment by Mateiadrielrafael** [comment]
oof, i rly want to use it w ts-node
