### ISSUE TITLE
Nested test suites fail

### ISSUE THREAD

**Issue by adelespinasse** [vpotseluyko/mjs-mocha#15]
Whenever I have nested `describe()` calls (test suites), the test seems to fail under mjs-mocha. For example, here's a test file that passes under regular Mocha:
```
describe('Do a test', () => {
  describe('Sub-suite', () => {
    it('should pass', () => {});
  });
});
```
But if I have a file ending with `.mjs` that is identical to the above, but with `import 'mjs-mocha';` added at the top, it fails.

I've set up a repo [here](https://github.com/adelespinasse/mjs-mocha-bug) to demonstrate. Run `npm test` to do the vanilla Mocha test. Run `npm run mjs-test` to run `mjs-mocha`.

The failure was intermittent (maybe 75% of the time) when I first discovered it in a real project, and it seemed not to happen unless the test suite used `before()` or `beforeEach()` or some such. With the artificial test linked above, it fails every time for me.

Using Mocha 6.1.4, mjs-mocha 2.2.4, Node 10.4.1, npm 6.9.0, on Ubuntu 16.04.

**Comment by vpotseluyko** [comment]
checkout version 3.0.0. It was uploaded to npm few minutes ago.
![image](https://user-images.githubusercontent.com/16744898/56870116-23db2c80-6a13-11e9-8d10-da47f8229ad8.png)

**Comment by vpotseluyko** [comment]
![image](https://user-images.githubusercontent.com/16744898/56870161-b2e84480-6a13-11e9-93ac-6aa68491b1fc.png)
nevermind, check v3.0.0.

**Comment by adelespinasse** [comment]
Wow, that was quick, thanks!

... but I think now it doesn't fail when it should? For example, if I change `a.test.mjs` to:
```
import 'mjs-mocha';

describe('Do a test', () => {
  describe('Sub-suite', () => {
    it('should fail', () => {
      throw new Error('fail');
    });
  });
});
```
or
```
import 'mjs-mocha';

describe('Do a test', () => {
  describe('Sub-suite', () => {
    it('should fail', () => {
      return Promise.reject(new Error('fail'));
    });
  });
});
```
running `mjs-mocha` seems to pass.

**Comment by adelespinasse** [comment]
Even a really simple suite, with no nested `describe`, seems to pass when it should fail.
```
import 'mjs-mocha';

describe('Do a test', () => {
  it('should fail', () => {
    throw new Error('fail');
  });
});
```

**Comment by vpotseluyko** [comment]
oh, it's awful. Thank you very much for report. I hope I'll fix it tonight

**Comment by vpotseluyko** [comment]
@adelespinasse try removing straight mjs-mocha import. Looks like it mixes contexts and fails.

**Comment by vpotseluyko** [comment]
here's test repo, run with `npm test`

https://github.com/vpotseluyko/mjs-mocha-example

**Comment by adelespinasse** [comment]
Oh, is it wrong to have `import 'mjs-mocha';`? In that case the README.md needs to be updated. But you're right, it works correctly when I remove the import. Thanks!

**Comment by vpotseluyko** [comment]
oh, I think import needed only when u call file via node. When calling through mocha itself no need. We will clarify readme. 
Any help wanted. Thanks
